name: Generate Stats

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '30 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'lll69/js-org-stats-generate'

    - uses: actions/setup-python@v6
      with:
        python-version: '3.12.3'

    - name: Clone js.org
      run: git clone https://github.com/js-org/js.org.git js.org

    - name: Generate
      run: |
        python pulls.py ${{ secrets.GITHUB_TOKEN }}
        python stat.py
        python svg.py

    - run: pip install -r requirements.txt

    - name: Push Stats
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: stat
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
